### ISSUE TITLE
Array arguments must have same length along one axis. Issue described by @13675070160

### ISSUE THREAD

**Issue by mirt001** [bfast2/geeMonitor#2]
As the picture shows that there have a problem When I export the GEE_Time_magnitudeOFchange. I found that Error: Array arguments must have same length along one axis.

**Comment by paulomur** [comment]
Hi all,
Yes, that error is very common. It occurs mostly when you export time break and in some cases with Mag of change. 
I used Sentinel2 TOA collection rather than Landsat but the error remains for both collections. I think the issue might be associated with overlapping areas between tiles. While Mag could be exported, timebreak never works.
It would be nice to receive some feedback about it.  

Thanks a lot!

**Comment by mpalvarezig** [comment]
Hi!!
After reading your comment @paulomur , i tried with a very small area wich has only one tile of Landsat and i obtain the same error when trying to export the breakTime image.
So, would be nice to receive some feedback for me too
Thanks in advance!

**Comment by hamun001** [comment]
There was a minor error with time layer. Can you try this code: https://code.earthengine.google.com/7e68c77bd8d5fe036e7594c73c1322bd
It should work.

**Comment by mpalvarezig** [comment]
I tried with different areas and i think it's working now
Thanks a lot!!

**Comment by hamun001** [comment]
I will now close this issue. Feel free to email me directly in case of any other issue at hamunyelae@unam.na
